# Generated by Django 3.1.1 on 2023-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numéro', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='commandemodel',
            name='Services',
            field=models.CharField(choices=[('1', 'Express'), ('2', 'Standard')], default='2', max_length=20),
        ),
    ]
