# Generated by Django 3.1.1 on 2023-08-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230727_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('name_enterprise', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
