# Generated by Django 3.1.1 on 2023-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('name_enterprise', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
