# Generated by Django 4.2.4 on 2023-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230807_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandemodel',
            name='Code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandemodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
